server:
  port: 8080

#develope
frontendDomain : "http://localhost:3000"
dbDomain : "mysql://localhost:3306"
dbUser: "root"
dbPassword: "1234"

#deploye
#frontendDomain : "http://localhost:3000"
#dbDomain : "mysql://localhost:3306"
#dbUser: "root"
#dbPassword: "1234"

spring:
  datasource:
    url: jdbc:${dbDomain}/portfolio?useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=utf-8&severTimezone=Asia/seoul
    username: ${dbUser}
    password: ${dbPassword}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  servlet:
    multipart:
      enabled: true
      location: "C:/Portfolio/boardimg"
      max-request-size: 100MB
      max-file-size: 20MB

  file:
    upload:
      path: "C:/Portfolio"

#ItemImg upload path
itemImgLocation : "C:/Portfolio/boardimg"

jwt:
  issuer: portfolio
  secret_key: sercretportfoliokey
